### ISSUE TITLE
Constants AppStrings

### ISSUE THREAD

**Issue by Dekablade01** [suho/surveys#10]
- Collecting static strings in a single file is not good at scale ✌️

**Comment by suho** [comment]
@Dekablade01 In this case, should I separate static strings for each screen? For example: SurveysString.swift, DetailString.swift? 
In case we have the same String using by more than 2 screen, do I need a SharedString.swift file?

**Comment by Dekablade01** [comment]
For `App.Color`, I recommend you to use style guide instead of set color's name with what it for. The reason is if you have hundred views using this color, you will need to create hundred of this color properties for each purpose. 

```
extension UIColor { 

    static var cardinalRed: UIColor? {
        return UIColor(hex: 0xCA202E)
    }

}
```

**Comment by Dekablade01** [comment]
For `App.String` how about we create a struct like `Constants` and create private extension for each view you want to use. 

With this you will able to see what are constants you're able and going to use in this viewController or views. This also help in encapsulation, because other viewControllers do not need to know about string for this view controller. Also you will able to find constants you're going to use easier. With your current implementation if you have hundreds of view controller you may have thousands of strings sharing across the app and you won't able to find what you want to use. 

```swift
// Constant.swift
struct Constants { } 
```

```swift
// ViewController.swift

final class ViewController: UIViewController { 

    private let constants = Constants.self
    private let button = UIButton() 

    override func viewDidLoad() { 
        super.viewDidLoad()
        button.setTitle(constants.takeSurvey, for: .normal)
    }

}

private extension Constants { 

    static var takeSurvey = "Take the survey"
    static var surveys = "Surveys"

}
```
