### ISSUE TITLE
Using Dependencies

### ISSUE THREAD

**Issue by Dekablade01** [suho/surveys#11]
- `SwifterSwift`, you're using this pod to for
    - `.trimmed` instead of `.trimmingCharacters(in: .whitespaces)`
    - `UIColor` init with `hex` and `rgba`
    - this is a large syntax sugar framework, all of helpers in this framework will be also included in the project
- `SVProgressHUD`
    - this can be replaced by `UIActivityIndicatorView`
- `SnapKit`, 
    - this is only used for making a constrains of `ISPageControl` on the `SurveysViewController` 
    - But this can be made by
        - make the right constraints in `.xib`
        - use NSLayoutConstrains. 
- `Kingfisher`, this is reasonable ✌️
- `ISPageControl`
    - but why you're not including this framework with cocoapods ?🤔

- Using dependencies is good !, but don't forget that you always need to rely on them and all their code will be in the project even you're using them or not ✌️

**Comment by suho** [comment]
@Dekablade01 Thanks for your review, I will remove these Pods and create needed functions 👍
And about ISPageControl, I found a bug so I fixed by my self and copy the source code into my project.
